apiVersion: v1
kind: Service
metadata:
  name: jaeger-nodeport
  namespace: simple-otel
spec:
  selector:
    app: jaeger
  type: NodePort
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
      nodePort: 31686