apiVersion: v1
kind: Service
metadata:
  name: otel-collector-nodeport
  namespace: simple-otel
spec:
  selector:
    app: otel-collector
  type: NodePort
  ports:
    - name: otlp-http
      port: 4318
      targetPort: 4318
      nodePort: 31318