FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./cmd

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=build /app/app /app/app
EXPOSE 9000
CMD ["/app/app"]